const publicRoutes: string[] = [
	"/jobs",
	"/job/:id",
	"/services",
	"/auth/login",
	"/service/:id",
	"/user/forgot-password/verify/:token",
	"/user/forgot-password/verify",
	"/user/forgot-password/reset-password/:token",
	"/seniors",
	"/senior/:id",
	"/news",
	"/news/:id",
	"/about",
	"/user/register",
	"/user/register/verify/:token",
	"/user/register/verify",
	"/user/forgot-password",
	"/user/confirm",
	"/user/verified",
	"/",
	"/categories",
];

export default publicRoutes;
